apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gluon-dashboard.fullname" . }}-http
  annotations:
    {{- toYaml .Values.http.annotations | nindent 4 }}
  labels:
    {{- include "gluon-dashboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  replicas: {{ toYaml .Values.http.replicas }}
  selector:
    matchLabels:
      {{- include "gluon-dashboard.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http
  template:
    metadata:
      annotations:
        {{- toYaml .Values.http.podAnnotations | nindent 8 }}
      labels:
        {{- include "gluon-dashboard.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: http
    spec:
      affinity:
        {{- toYaml .Values.http.affinity | nindent 8 }}
      containers:
      - name: app
        image: {{ toYaml (print .Values.image.repository ":" .Values.image.tag) }}
        imagePullPolicy: {{ toYaml .Values.image.pullPolicy }}
        lifecycle:
          {{- toYaml .Values.http.lifecycle | nindent 10 }}
        ports:
        - name: http
          containerPort: 80
        resources:
          {{- toYaml .Values.http.resources | nindent 10 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.http.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.http.tolerations | nindent 8 }}
